version: "3.8"

services:
  carriel:
    image: ghcr.io/santiagoalomoto/alomoto-carriel-examen:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"

        # Enrutamiento HTTP → HTTPS
        - "traefik.http.routers.carriel.entrypoints=http"
        - "traefik.http.routers.carriel.rule=Host(`carriel.byronrm.com`)"
        - "traefik.http.middlewares.carriel-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.carriel.middlewares=carriel-https-redirect"

        # HTTPS con certificado automático Let's Encrypt
        - "traefik.http.routers.carriel-secure.entrypoints=https"
        - "traefik.http.routers.carriel-secure.rule=Host(`carriel.byronrm.com`)"
        - "traefik.http.routers.carriel-secure.tls=true"
        - "traefik.http.routers.carriel-secure.tls.certresolver=http"
        - "traefik.http.routers.carriel-secure.service=carriel"

        # Puerto interno donde corre tu app (Node.js → 3000)
        - "traefik.http.services.carriel.loadbalancer.server.port=3000"

        # Red pública del traefik
        - "traefik.docker.network=traefik-public"

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
